routes/admin.php
<?php

use Illuminate\Support\Facades\Route;


Route::namespace("\App\Http\Controllers\Back")->middleware(["auth","auth.admin"])->prefix("admin")->as("admin.")
    ->group(function () {

        Route::get("/", "DashboardController@index")->name("dashboard.index");

        Route::get("users/getUsers", "UserController@getUsers")->name("users.getUsers");
        Route::resource("users", "UserController")->except(["update", "store","destroy"]);
        Route::match(['PUT', "POST"], "users", "UserController@store")->name("users.store");
        Route::get("users/{user}/destroy", "UserController@destroy")->name("users.destroy");
        Route::get("users/{user}/archive", "UserController@archive")->name("users.archive");
        Route::get("users/{user}/recycle", "UserController@recycle")->name("users.recycle");
        Route::get("users/archived/list", "UserController@archivedList")->name("users.archive.index");
        Route::get("users/schedule/{user}", "UserController@scheduleForm")->name("users.schedule.form");

        Route::get("search/users", "SearchController@searchForUser")->name("search.users");

        Route::get("credits", "CreditController@index")->name("credits.index");

        Route::get("credits/show/{credit}", "CreditController@show")->name("credits.show");
        Route::post("credits/addCharge/{credit}", "CreditController@addCharge")->name("credits.addCharge");
        Route::get("credits/createUniqueUrl/{credit}", "CreditController@createUniqueUrl")->name("credits.createUniqueUrl");

        Route::get("creditGroups", "CreditGroupController@index")->name("creditGroups.index");
        Route::get("creditGroups/create", "CreditGroupController@create")->name("creditGroups.create");
        Route::post("creditGroups/{creditGroup}/createPins", "CreditGroupController@storePins")->name("creditGroups.storePins");
        Route::get("creditGroups/{creditGroup}/getCredits", "CreditGroupController@getGreditsOfGroup")->name("creditGroups.getCreditsOfGroup");
        Route::get("creditGroups/{creditGroup}/destroy", "CreditGroupController@destroy")->name("creditGroups.destroy");

        Route::get("creditGroups/{creditGroup}", "CreditGroupController@show")->name("creditGroups.show");
        Route::post("creditGroups", "CreditGroupController@store")->name("creditGroups.store");
        Route::get("creditGroups/{creditGroup}/download", "CreditGroupController@download")->name("creditGroups.download");


        Route::resource("queues", "QueueController")->except(["update", "store","destroy"]);
        Route::match(['PUT', "POST"], "queues", "QueueController@store")->name("queues.store");
        Route::get("queues/{queue}/destroy", "QueueController@destroy")->name("queues.destroy");
        Route::post("queues/addUser", "QueueController@addUser")->name("queues.add");
        Route::post("queues/changeStatus", "QueueController@changeStatus")->name("queues.changeStatus");
        Route::delete("queues/users/removeFromQueue", "QueueController@removeUserFromQueue")->name("queues.removeUserFromQueue");

        Route::get("calls","CallController@index")->name("calls.index");
        Route::get("calls/getCalls","CallController@getCalls")->name("calls.getCalls");
        Route::get("calls/{call}","CallController@show")->name("calls.show");

        Route::get("reports/calls", "ReportController@calls");

        Route::get("changePassword", "PasswordController@form")->name("changePasswordForm");
        Route::post("changePassword", "PasswordController@update")->name("changePassword");

        Route::get("search", "SearchController@search")->name("search");

        Route::get("options", "OptionsController@index")->name("options.index");
        Route::post("options", "OptionsController@store")->name("options.store");

    });

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::namespace("\App\Http\Controllers\Front")->as("front.")
    ->group(function () {
        Route::get("/", "HomeController@index")->name("home.index");

        Route::post("/purchase", "PurchaseController@purchase")->name("purchase");
        Route::get("/purchase/verify/{driver}", "PurchaseController@verify")->name("purchase.verify");

        Route::get("/credits/{unique_id}", "CreditController@show")->name("credits.show");
        Route::post("/credits/updatePhoneNumber", "CreditController@updatePhoneNumber")->name("credits.updatePhoneNumber");

        Route::get("/payments/fails", "PaymentController@fails")->name("payments.fails");

        Route::get("syncQueues", function () {
            $sync = new \App\Classes\Simotel\SyncUsersInQueues();
            $sync->syncAll();
        });

    });

Auth::routes(["register" => false]);

Route::any("/clear", function () {
    \Illuminate\Support\Facades\Artisan::call("view:clear");
});
Route::any("/migrate/fresh", function () {
    \Illuminate\Support\Facades\Artisan::call("migrate:fresh");
});

Route::get("shetabit/start", "ShetabitTestController@start");
Route::get("shetabit/verify", "ShetabitTestController@verify")->name("shetabit.verify");

Route::get("users/test", "TestController@users");
Route::get("users/data", "TestController@usersData")->name("users.data");

Route::get("fields", function () {
    $class = new \App\Classes\Simotel\SimotelSettings();
    dd($class->getGroupedFields());
});

Route::get("firstuser", function () {
    $user = \App\User::find(1);
    $user->level = \App\User::LEVEL_ADMIN;
    $user->password = bcrypt("asd123ASD");
    $user->save();
});

Route::get("createuseradmin", function () {
    if(\App\User::count()>0)
        die("exists");

    \App\User::create([
        'name' => 'username',
        'email' => request("email"),
        'password' => bcrypt("asd123ASD"),
        'simotel_number' => "",
        'mobile' => "",
        'comment' => "",
        'address' => "تهران، آدرس مربوط به محل کاربر ادمین",
        'level' =>  \App\User::LEVEL_ADMIN,
        'entrance_fee' => "1000",
        'credit_ratio' => "1000",
    ]);

});

Route::get("logtest", function () {
    \Illuminate\Support\Facades\Log::info("test");
});


Route::get("ternary", function () {
    return view("ternary");
});


Route::get("/test/simotel","TestController@simotel");

app/Models/Call.php
<?php

namespace App\Models;

use App\User;
use Baloot\EloquentHelper;
use Carbon\CarbonInterval;
use Illuminate\Database\Eloquent\Model;

class Call extends Model
{
    use EloquentHelper;


    public function putCredit($credit)
    {
        $this->credit_id = $credit->id;
        $this->save();
    }

    public function queue()
    {
        return $this->belongsTo(Queue::class)->withDefault(['name' => ""]);
    }

    public function user()
    {
        return $this->belongsTo(User::class)->withDefault(['name' => ""]);
    }


    public function getCallTimeReadableShortAttribute()
    {
        return $this["call_time"] ? secondsToShortTime($this["call_time"]) : "0";
    }

    public function getCallTimeReadableAttribute()
    {
        return $this["call_time"] ? CarbonInterval::seconds($this['call_time'])->cascade()->forHumans() : "0";
    }
    public function getTotalAmountReadableAttribute()
    {
        return number_format($this["total_amount"]);
    }

    function getHoursMinutes($seconds)
    {

        $hours = floor($seconds / 3600);
        $minutes = floor(($seconds - ($hours * 60 * 60)) / 60);
        $seconds = $seconds - $hours*3600 - $minutes*60;
        return sprintf("%d:%d:%d",
            $hours,
            $minutes,
            $seconds
        );
    }

    public function credit(){
        return $this->belongsTo(Credit::class);
    }

    protected $casts = [
        'create_date' => 'date',
    ];
}

app/Models/Schedule.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Schedule extends Model
{

    public function getDayReadableAttribute()
    {
        return [
            "شنبه",
            "یکشنبه",
            "دوشنبه",
            "سه شنبه",
            "چهار شنبه",
            "پنجشنبه",
            "جمعه",
        ][$this['day'] - 1];
    }

    public function getStartTimeFormattedAttribute()
    {
        $arr = explode(":", $this['start_time']);
        unset($arr[2]);
        return implode(":", $arr);
    }

    public function getEndTimeFormattedAttribute()
    {
        $arr = explode(":", $this['end_time']);
        unset($arr[2]);
        return implode(":", $arr);
    }


    public function scopeGregorianDay($q, $day)
    {
        $persianDay = ($day) % 7 + 2;
        return $q->where("day", $persianDay);
    }


    public function scopeOverlappedWith($q, $startTime, $endTime, $day)
    {
        return $q
            ->where("day", $day)
            ->where(function ($q) use ($startTime, $endTime) {
                return $q
                    ->orWhere(function ($q) use ($startTime, $endTime) {
                        return $q->whereTime("start_time", "<=", $startTime)
                            ->whereTime("end_time", ">=", $startTime);
                    })
                    ->orWhere(function ($q) use ($startTime, $endTime) {
                        return $q->whereTime("start_time", "<=", $endTime)
                            ->whereTime("end_time", ">=", $endTime);
                    })
                    ->orWhere(function ($q) use ($startTime, $endTime) {
                        return $q->whereTime("start_time", ">=", $startTime)
                            ->whereTime("end_time", "<=", $endTime);
                    });
            });
    }

}

app/Http/Controllers/Advisor/UserController.php
<?php

namespace App\Http\Controllers\Advisor;

use App\Classes\Simotel\SyncUsersInQueues;
use App\Http\Controllers\Controller;
use App\Models\Queue;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class UserController extends Controller
{
    public function profile()
    {
        $user = Auth::user();
        $userQueues = $user->queues()->withCount("users")->get();
        $callsInQueuesReport = Queue::select(DB::raw(
            "queues.id, queues.name , sum(calls.call_time) as calls_time_total ,avg(calls.call_time) as calls_time_avg ,avg(calls.poll_score) as poll_score_avg "
        ))
            ->join("calls", "queues.id", "=", "calls.queue_id")->where("calls.user_id", $user->id)
            ->groupBy("queues.id", "queues.name")->orderBy("calls.call_time")->get()->dd();
    }


    public function changeStatus(Request $request)
    {
        $this->validate($request, [
            "active" => "required|boolean",
        ]);

        $pause = !$request->active;

        $user = Auth::user();
        $user->simotel_paused = $pause;
        $user->save();

        $simotel = new SyncUsersInQueues;

        if ($pause)
            $simotel->pauseUser($user);
        else
            $simotel->unpauseUser($user);


        return response()->json([
            "active" => !$pause
        ]);
    }

    public function schedules()
    {
        $user = Auth::user();
        return view("advisor.schedules.all", compact("user"));
    }
}

app/Http/Controllers/Back/AdvisorQueueController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AdvisorQueueController extends Controller
{
    public function __construct()
    {
    }

    public function index()
    {
        $user = Auth::user();

        $queues =
            $user
                ->queues()
                ->join("calls", "queues.id", "calls.queue_id")
                ->join("calls","users.id","calls.user_id")
        ->get();
        dd($queues);
    }
}

app/Http/Controllers/Back/CallController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\Models\Call;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Yajra\DataTables\Facades\DataTables;

class CallController extends Controller
{
    public function index()
    {
        return view("back.calls.all");
    }

    public function getCalls()
    {
        $calls = Call::select(DB::raw("calls.* , users.name as user_name , queues.name as queue_name"))
            ->join("queues", "queues.id", "calls.queue_id")
            ->join("users", "users.id", "calls.user_id");

        return DataTables::of($calls)

            ->addColumn('user_name_str', function ($row) {
                return "<a href='" . route("admin.users.show", $row->user_id) . "'>$row->user_name</a>";
            })
            ->addColumn('queue_name_str', function ($row) {
                return "<a href='" . route("admin.queues.show", $row->queue_id) . "'>$row->queue_name</a>";
            })
            ->addColumn('created_at_fa_ftt', function ($row) {
                return "<a href='" . route("admin.calls.show", $row->id) . "'>$row->created_at_fa_ftt</a>";
            })
            ->addColumn('call_time_readable', function ($row) {
                return $row->call_time_readable_short;
            })
            ->addColumn('total_amount_formatted', function ($row) {
                return number_format($row->total_amount);
            })

            ->rawColumns(['user_name_str', "queue_name_str","created_at_fa_ftt"])
            ->make(true);
    }

    public function show()
    {

    }
}

app/Http/Controllers/Back/CreditController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\Models\Call;
use App\Models\Credit;
use App\Models\CreditCharges;
use App\Models\CreditGroup;
use App\Models\CreditGroups;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class CreditController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $credits = Credit
            ::select(
                DB::raw("`credits`.`id`,`identifier`,sum(`credit_charges`.`amount`) as `sum_credit` , sum(`calls`.`total_amount`) as `total_usage` ")
            )
            ->join('credit_charges', 'credits.id', "=", "credit_charges.credit_id")
            ->leftJoin("calls", 'credits.id', '=', 'calls.credit_id')
            ->groupBy("credits.id")
            ->get();
        return view("back.credits.all", compact("credits"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
 /*   public function create()
    {
        $credit = new Credit();
        return view("back.credits.create", compact("credit"));
    }*/

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
 /*   public function store(Request $request)
    {

        $this->validate($request,
            [
                "amount" => "required|numeric",
            ]
        );

       Credit::createNew($request->amount,$request->customer_number);

        return self::redirectWithSuccess(route("admin.credits.index"), "اطلاعات ذخیره شد");
    }*/

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Credit $credit
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Credit $credit)
    {
        $credit->load("charges", "calls", 'calls.user', 'calls.queue');
        return view("back.credits.show", compact('credit'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Credit $credit
     * @return \Illuminate\Http\Response
     */
    public function edit(Credit $credit)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Credit $credit
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Credit $credit)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Credit $credit
     * @return \Illuminate\Http\Response
     */
    public function destroy(Credit $credit)
    {
        //
    }


    public function addCharge(Request $request, Credit $credit)
    {
        $this->validate($request, [
            'amount' => "required|numeric"
        ]);
        $credit->charges()->create([
            'amount' => $request->amount,
            'comment' => $request->comment,
            'creator_id' => Auth::user() ? Auth::user()->id : null ,
        ]);

        return self::redirectBackWithSuccess("عملیات شارژ انجام شد");
    }


    public function createUniqueUrl(Credit $credit)
    {
        $credit->changeUniqueId();
        return self::redirectBackWithSuccess("لینک منحصر به فرد ایجاد شد.");
    }

}

app/Http/Controllers/Back/OptionsController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class OptionsController extends Controller
{
    public function index()
    {
        return view("back.options.index");
    }

    public function store(Request $request)
    {

        \Options::group("site-options")->set("site-name", $request["site-name"]);
        \Options::group("site-options")->set("zarinpal-mode", $request["zarinpal-mode"]);
        \Options::group("site-options")->set("zarinpal-merchant", $request["zarinpal-merchant"]);
        \Options::group("site-options")->set("credit-plans", $request["credit_plans"]);
        return self::redirectBackWithSuccess("ذخیره شد");

    }
}

resources/views/back/users/all.blade.php
@extends("back.layout.app")
@section("content_header")
    @component("components.breadcrump",["items"=> ["Dashboard" =>route("admin.dashboard.index"),"current"=>"کاربران"]])
        <a href="{{ route("admin.users.create") }}" class="btn btn-info btn-sm">جدید</a>
    @endcomponent
@endsection

@section("content")
    <x-success></x-success>
    <div class="card">
        <div class="card-body">
            <table class="table usersTable">
                <thead>
                <tr>
                    <th>نام</th>
                    <th>ایمیل</th>
                    <th>شماره سیموتل</th>
                    <th>تعداد صف</th>
                    <th>شماره موبایل</th>
                    <th>توضیجات</th>
                </tr>
                </thead>
                <tbody>

                </tbody>
            </table>
        </div>
    </div>
@endsection
@push('js')
    <script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>

    <script type="text/javascript">
        $(function () {
            var table = $('.usersTable').DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{ route('admin.users.getUsers') }}",
                columns: [
                    {data: 'user_name', name: 'name'},
                    {data: 'email', name: 'email'},
                    {data: 'simotel_number', name: 'simotel_number'},
                    {data: 'queues_count', name: 'queues_count'},
                    {data: 'mobile', name: 'mobile'},
                    {data: 'comment', name: 'comment'},
                ]
            });

        });
    </script>

@endpush

resources/views/back/users/show.blade.php
@extends("back.layout.app")
@section("content_header")
    @component("components.breadcrump",
    ["items"=> ["Dashboard" =>route("admin.dashboard.index"),"Users" =>route("admin.users.index"),"current"=>"مشاهده وضعیت کاربر"]])
    @endcomponent
@endsection
@section("content")
    <style>
        .card-footer.form {
            background-color: rgba(53, 29, 2, 0.3) !important;
        }
    </style>

    <x-success></x-success>

    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">

                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-2 col-4 col-xs-offset-3 col-lg-4 col-xl-2">
                            <img src="/images/avatar-placeholder.png" alt="" class="w-100 rounded-circle">
                        </div>
                        <div class="col-md-10 col-lg-8 col-xl-10">
                            <div class="text-success h4"><i class="fa fa-user"></i> {{ $user->name }} </div>
                            {{ Html::info()->value($user->mobile)->label("شماره موبایل")->icon("mobile") }}
                            {{ Html::info()->value($user->simotel_number)->label("داخلی سیموتل")->icon("phone") }}
                            {{ Html::info()->value($user->comment)->label("توضیحات")->icon("info") }}
                            {{ Html::info()->value($user->created_at_fa_ftt)->label("زمان ثبت نام کاربر")->icon("plus") }}
                            {{ Html::info()->value($user->updated_at_fa_ftt)->label("زمان آخرین ویرایش")->icon("edit") }}
                            {{ Html::info()->value($user->simotel_paused ? "فعال" : "در استراحت")->label("وضعیت کاربر (استراحت)")->icon("user") }}
                            {{ Html::info()->value($user->credit_ratio)->label("ضریب کسر اعتبار")->icon("dollar") }}
                            {{ Html::info()->value($user->entrance_fee)->label("هزینه ورودی")->icon("money") }}


                        </div>
                    </div>

                </div>
                <div class="card-footer">
                    <div class="float-left">
                        <a class="btn btn-outline-success btn-sm" href="{{ route("admin.users.edit",$user) }}"><i
                                class="fa fa-edit"></i> ویرایش مشخصات </a>
                                <a class="btn btn-warning btn-sm" href="{{ route("admin.users.archive",$user) }}"><i
                                class="fa fa-recycle"></i> آرشیو</a>
                                <a class="btn btn-danger btn-sm confirmation" href="{{ route("admin.users.destroy",$user) }}"><i
                                class="fa fa-trash"></i> حذف دائم</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="row">

                <div class="col-md-6 col-xs-12">
                    <div class="info-box">
                        <span class="info-box-icon bg-success"><i class="fa fa-phone"></i></span>
                        <div class="info-box-content">
                            <span class="info-box-text">کل زمان مکالمات</span>
                            <span class="info-box-number">{{ $callsReport->call_time_readable_short }}</span>
                        </div>
                        <!-- /.info-box-content -->
                    </div>
                    <!-- /.info-box -->
                </div>
                <div class="col-md-6 col-xs-12">
                    <div class="info-box">
                        <span class="info-box-icon bg-danger"><i class="fa fa-star"></i></span>

                        <div class="info-box-content">
                            <span class="info-box-text">میانگین امتیاز</span>
                            <span class="info-box-number">{{ round($callsReport->poll_score_avg,1) }}</span>
                        </div>
                        <!-- /.info-box-content -->
                    </div>
                    <!-- /.info-box -->
                </div>
                <div class="col-md-6 col-xs-12">
                    <div class="info-box">
                        <span class="info-box-icon bg-secondary"><i class="fa fa-phone"></i></span>

                        <div class="info-box-content">
                            <span class="info-box-text">تعداد تماس ها</span>
                            <span class="info-box-number">{{ $callsReport->calls_count }}</span>
                        </div>
                        <!-- /.info-box-content -->
                    </div>
                    <!-- /.info-box -->
                </div>
                <div class="col-md-6 col-xs-12">
                    <div class="info-box">
                        <span class="info-box-icon bg-info"><i class="fa fa-phone"></i></span>

                        <div class="info-box-content">
                            <span class="info-box-text">میانگین زمان مکالمات</span>
                            <span class="info-box-number">{{ $callsReport->average_call_time_readable }}</span>
                        </div>
                        <!-- /.info-box-content -->
                    </div>
                    <!-- /.info-box -->
                </div>
                <div class="col-md-6 col-xs-12">
                    <div class="info-box">
                        <span class="info-box-icon bg-warning"><i class="fa fa-coins"></i></span>

                        <div class="info-box-content">
                            <span class="info-box-text">درآمد</span>
                            <span class="info-box-number">{{ $callsReport->total_amount }}</span>
                        </div>
                        <!-- /.info-box-content -->
                    </div>
                    <!-- /.info-box -->
                </div>
            </div>
        </div>
        <!-- /.col -->
    </div>


    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">صف های فعال</div>
                <div class="card-body">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>نام صف</th>
                            <th>تعداد مشاور</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($userQueues as $queue)
                            <tr>
                                <td>{{ $queue->name }}</td>
                                <td>{{ $queue->users_count }}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">گزارش مکالمات در صف ها</div>
                <div class="card-body">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>نام صف</th>
                            <th>مجموع زمان مکالمه</th>
                            <th>میانگین زمان مکالمه</th>
                            <th>میتگین امتیاز</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($callsInQueuesReport as $report)
                            <tr>
                                <td>{{ $report->name }}</td>
                                <td>{{ secondsToShortTime($report->calls_time_total) }}</td>
                                <td>{{ secondsToShortTime($report->calls_time_avg) }}</td>
                                <td>{{ round($report->poll_score_avg,1) }}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">آخرین تماس ها</div>
                <div class="card-body">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>شناسه مکالمه</th>
                            <th>صف</th>
                            <th>مدت مکالمه</th>
                            <th>امتیاز</th>
                            <th>زمان شروع</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($userLastCalls as $call)
                            <tr>
                                <td>{{ $call->id }}</td>
                                <td>{{ $call->queue->name }}</td>
                                <td>{{ $call->call_time_readable_short }}</td>
                                <td>{{ $call->poll_score }}</td>
                                <td>{{ $call->created_at_fa_ftt }}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>


        <div class="col-md-6">
            <div class="card">
                <div class="card-header">برنامه حضور
                    <a href="{{ route("admin.users.schedule.form",$user) }}" class="btn btn-sm btn-outline-primary float-left">
                        تنظیم برنامه
                    </a>
                </div>

                <div class="card-body">
                    <table class="table ">
                        <thead>
                        <tr>
                            <th>روز هفته</th>
                            <th>شروع</th>
                            <th>پایان</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($user->schedules as $schedule)
                            <tr>
                                <td>{{ $schedule->day_readable }}</td>
                                <td>{{ $schedule->start_time_formatted }}</td>
                                <td>{{ $schedule->end_time_formatted }}</td>

                            </tr>
                        @endforeach
                        </tbody>
                    </table>


                </div>
            </div>
        </div>


    </div>

@endsection
@section("adminlte_js")
<script>
    $(document).ready(function(){
        $(".need_confirm").click(function(e){
            if(!confirm("آیا مطمئن هستید؟"))
            {
                e.preventDefault();
            }
        })
    })
</script>
@endsection

resources/views/back/users/trash.blade.php
@extends("back.layout.app")
@section("content_header")
    @component("components.breadcrump",
    ["items"=> ["Dashboard" =>route("admin.dashboard.index"),"Users" =>route("admin.users.index"),"current"=>"آرشیو کاربران"]])
    @endcomponent
@endsection

@section("content")
    <x-success></x-success>
    <div class="card">
        <div class="card-body">

            {{ $users->render() }}
            <table class="table">
                <thead>
                <tr>
                    <th></th>
                    <th>نام</th>
                    <th>تعداد نماد</th>
                    <th>شماره موبایل</th>
                    <th>تاریخ شروع پشتیبانی</th>
                    <th>تاریخ اتمام</th>
                    <th></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                @foreach($users as $user)
                    <tr>
                        <td></td>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->symbols_count }}</td>
                        <td>{{ $user->mobile }}</td>
                        <td>{{ $user->support_start_fa_f }}</td>
                        <td>{{ $user->support_end_fa_f }}</td>
                        <td><a href="{{ route("admin.users.recycle",$user) }}">خروج از آرشیو</a></td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection