routes/admin.php
<?php

use Illuminate\Support\Facades\Route;


Route::namespace("\App\Http\Controllers\Back")->middleware(["auth","auth.admin"])->prefix("admin")->as("admin.")
    ->group(function () {

        Route::get("/", "DashboardController@index")->name("dashboard.index");

        Route::get("users/getUsers", "UserController@getUsers")->name("users.getUsers");
        Route::resource("users", "UserController")->except(["update", "store","destroy"]);
        Route::match(['PUT', "POST"], "users", "UserController@store")->name("users.store");
        Route::get("users/{user}/destroy", "UserController@destroy")->name("users.destroy");
        Route::get("users/{user}/archive", "UserController@archive")->name("users.archive");
        Route::get("users/{user}/recycle", "UserController@recycle")->name("users.recycle");
        Route::get("users/archived/list", "UserController@archivedList")->name("users.archive.index");
        Route::get("users/schedule/{user}", "UserController@scheduleForm")->name("users.schedule.form");

        Route::get("search/users", "SearchController@searchForUser")->name("search.users");

        Route::get("credits", "CreditController@index")->name("credits.index");

        Route::get("credits/show/{credit}", "CreditController@show")->name("credits.show");
        Route::post("credits/addCharge/{credit}", "CreditController@addCharge")->name("credits.addCharge");
        Route::get("credits/createUniqueUrl/{credit}", "CreditController@createUniqueUrl")->name("credits.createUniqueUrl");

        Route::get("creditGroups", "CreditGroupController@index")->name("creditGroups.index");
        Route::get("creditGroups/create", "CreditGroupController@create")->name("creditGroups.create");
        Route::post("creditGroups/{creditGroup}/createPins", "CreditGroupController@storePins")->name("creditGroups.storePins");
        Route::get("creditGroups/{creditGroup}/getCredits", "CreditGroupController@getGreditsOfGroup")->name("creditGroups.getCreditsOfGroup");
        Route::get("creditGroups/{creditGroup}/destroy", "CreditGroupController@destroy")->name("creditGroups.destroy");

        Route::get("creditGroups/{creditGroup}", "CreditGroupController@show")->name("creditGroups.show");
        Route::post("creditGroups", "CreditGroupController@store")->name("creditGroups.store");
        Route::get("creditGroups/{creditGroup}/download", "CreditGroupController@download")->name("creditGroups.download");


        Route::resource("queues", "QueueController")->except(["update", "store","destroy"]);
        Route::match(['PUT', "POST"], "queues", "QueueController@store")->name("queues.store");
        Route::get("queues/{queue}/destroy", "QueueController@destroy")->name("queues.destroy");
        Route::post("queues/addUser", "QueueController@addUser")->name("queues.add");
        Route::post("queues/changeStatus", "QueueController@changeStatus")->name("queues.changeStatus");
        Route::delete("queues/users/removeFromQueue", "QueueController@removeUserFromQueue")->name("queues.removeUserFromQueue");

        Route::get("calls","CallController@index")->name("calls.index");
        Route::get("calls/getCalls","CallController@getCalls")->name("calls.getCalls");
        Route::get("calls/{call}","CallController@show")->name("calls.show");

        Route::get("reports/calls", "ReportController@calls");

        Route::get("changePassword", "PasswordController@form")->name("changePasswordForm");
        Route::post("changePassword", "PasswordController@update")->name("changePassword");

        Route::get("search", "SearchController@search")->name("search");

        Route::get("options", "OptionsController@index")->name("options.index");
        Route::post("options", "OptionsController@store")->name("options.store");

    });

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::namespace("\App\Http\Controllers\Front")->as("front.")
    ->group(function () {
        Route::get("/", "HomeController@index")->name("home.index");

        Route::post("/purchase", "PurchaseController@purchase")->name("purchase");
        Route::get("/purchase/verify/{driver}", "PurchaseController@verify")->name("purchase.verify");

        Route::get("/credits/{unique_id}", "CreditController@show")->name("credits.show");
        Route::post("/credits/updatePhoneNumber", "CreditController@updatePhoneNumber")->name("credits.updatePhoneNumber");

        Route::get("/payments/fails", "PaymentController@fails")->name("payments.fails");

        Route::get("syncQueues", function () {
            $sync = new \App\Classes\Simotel\SyncUsersInQueues();
            $sync->syncAll();
        });

    });

Auth::routes(["register" => false]);

Route::any("/clear", function () {
    \Illuminate\Support\Facades\Artisan::call("view:clear");
});
Route::any("/migrate/fresh", function () {
    \Illuminate\Support\Facades\Artisan::call("migrate:fresh");
});

Route::get("shetabit/start", "ShetabitTestController@start");
Route::get("shetabit/verify", "ShetabitTestController@verify")->name("shetabit.verify");

Route::get("users/test", "TestController@users");
Route::get("users/data", "TestController@usersData")->name("users.data");

Route::get("fields", function () {
    $class = new \App\Classes\Simotel\SimotelSettings();
    dd($class->getGroupedFields());
});

Route::get("firstuser", function () {
    $user = \App\User::find(1);
    $user->level = \App\User::LEVEL_ADMIN;
    $user->password = bcrypt("asd123ASD");
    $user->save();
});

Route::get("createuseradmin", function () {
    if(\App\User::count()>0)
        die("exists");

    \App\User::create([
        'name' => 'username',
        'email' => request("email"),
        'password' => bcrypt("asd123ASD"),
        'simotel_number' => "",
        'mobile' => "",
        'comment' => "",
        'address' => "تهران، آدرس مربوط به محل کاربر ادمین",
        'level' =>  \App\User::LEVEL_ADMIN,
        'entrance_fee' => "1000",
        'credit_ratio' => "1000",
    ]);

});

Route::get("logtest", function () {
    \Illuminate\Support\Facades\Log::info("test");
});


Route::get("ternary", function () {
    return view("ternary");
});


Route::get("/test/simotel","TestController@simotel");

app/Models/Call.php
<?php

namespace App\Models;

use App\User;
use Baloot\EloquentHelper;
use Carbon\CarbonInterval;
use Illuminate\Database\Eloquent\Model;

class Call extends Model
{
    use EloquentHelper;


    public function putCredit($credit)
    {
        $this->credit_id = $credit->id;
        $this->save();
    }

    public function queue()
    {
        return $this->belongsTo(Queue::class)->withDefault(['name' => ""]);
    }

    public function user()
    {
        return $this->belongsTo(User::class)->withDefault(['name' => ""]);
    }


    public function getCallTimeReadableShortAttribute()
    {
        return $this["call_time"] ? secondsToShortTime($this["call_time"]) : "0";
    }

    public function getCallTimeReadableAttribute()
    {
        return $this["call_time"] ? CarbonInterval::seconds($this['call_time'])->cascade()->forHumans() : "0";
    }
    public function getTotalAmountReadableAttribute()
    {
        return number_format($this["total_amount"]);
    }

    function getHoursMinutes($seconds)
    {

        $hours = floor($seconds / 3600);
        $minutes = floor(($seconds - ($hours * 60 * 60)) / 60);
        $seconds = $seconds - $hours*3600 - $minutes*60;
        return sprintf("%d:%d:%d",
            $hours,
            $minutes,
            $seconds
        );
    }

    public function credit(){
        return $this->belongsTo(Credit::class);
    }

    protected $casts = [
        'create_date' => 'date',
    ];
}

app/Http/Controllers/Back/AdvisorQueueController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AdvisorQueueController extends Controller
{
    public function __construct()
    {
    }

    public function index()
    {
        $user = Auth::user();

        $queues =
            $user
                ->queues()
                ->join("calls", "queues.id", "calls.queue_id")
                ->join("calls","users.id","calls.user_id")
        ->get();
        dd($queues);
    }
}

app/Http/Controllers/Back/CallController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\Models\Call;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Yajra\DataTables\Facades\DataTables;

class CallController extends Controller
{
    public function index()
    {
        return view("back.calls.all");
    }

    public function getCalls()
    {
        $calls = Call::select(DB::raw("calls.* , users.name as user_name , queues.name as queue_name"))
            ->join("queues", "queues.id", "calls.queue_id")
            ->join("users", "users.id", "calls.user_id");

        return DataTables::of($calls)

            ->addColumn('user_name_str', function ($row) {
                return "<a href='" . route("admin.users.show", $row->user_id) . "'>$row->user_name</a>";
            })
            ->addColumn('queue_name_str', function ($row) {
                return "<a href='" . route("admin.queues.show", $row->queue_id) . "'>$row->queue_name</a>";
            })
            ->addColumn('created_at_fa_ftt', function ($row) {
                return "<a href='" . route("admin.calls.show", $row->id) . "'>$row->created_at_fa_ftt</a>";
            })
            ->addColumn('call_time_readable', function ($row) {
                return $row->call_time_readable_short;
            })
            ->addColumn('total_amount_formatted', function ($row) {
                return number_format($row->total_amount);
            })

            ->rawColumns(['user_name_str', "queue_name_str","created_at_fa_ftt"])
            ->make(true);
    }

    public function show()
    {

    }
}

app/Http/Controllers/Back/OptionsController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class OptionsController extends Controller
{
    public function index()
    {
        return view("back.options.index");
    }

    public function store(Request $request)
    {

        \Options::group("site-options")->set("site-name", $request["site-name"]);
        \Options::group("site-options")->set("zarinpal-mode", $request["zarinpal-mode"]);
        \Options::group("site-options")->set("zarinpal-merchant", $request["zarinpal-merchant"]);
        \Options::group("site-options")->set("credit-plans", $request["credit_plans"]);
        return self::redirectBackWithSuccess("ذخیره شد");

    }
}

app/Http/Controllers/Back/QueueController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\Models\Queue;
use App\User;
use Hsy\SimotelConnect\SimotelApi;
use Illuminate\Http\Request;
use Illuminate\Support\MessageBag;

class QueueController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $queues = Queue::withCount("users")->paginate(100);
        return view("back.queues.all", compact("queues"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        $queue = new Queue;
        return view("back.queues.create", compact("queue"));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {
        $queue = $request->isMethod("POST") ? new Queue : Queue::findOrFail($request->queue_id);
        $this->validate($request,
            [
                "announcement_id" => "required|integer|unique:queues,announcement_id," . $queue->id,
                "name" => "required",
                "simotel_number" => "sometimes|nullable|unique:queues,simotel_number," . $queue->id,
            ]
        );

        $queue->announcement_id = $request->announcement_id;
        $queue->name = $request->name;
        $queue->simotel_number = $request->simotel_number;
        $queue->entrance_fee = $request->entrance_fee;
        $queue->credit_ratio = $request->credit_ratio;
        $queue->active = true;
        $queue->comment = $request->comment;
        $queue->save();
        return self::redirectWithSuccess(route("admin.queues.index"), "اطلاعات ذخیره شد");

    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Queue $queue
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Queue $queue)
    {
        return view("back.queues.show", compact("queue"));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Queue $queue
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Queue $queue)
    {
        return view("back.queues.edit", compact("queue"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Queue $queue
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Queue $queue)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Queue $queue
     * @return \Illuminate\Http\Response
     */
    public function destroy(Queue $queue)
    {
        $queue->users()->detach();
        $queue->delete();
        return self::redirectWithSuccess(route("admin.queues.index"), "حذف شد.");
    }

    /* public function archive(Queue $queue)
     {
         ///soft delete
         $queue->delete();
         return self::redirectWithSuccess(route("admin.queues.archive.index"), "آرشیو شد");
     }*/

    /* public function recycle($user_id)
     {
         $queue = Queue::withTrashed()->findOrFail($user_id);
         $queue->restore();
         return self::redirectWithSuccess(route("admin.queues.show", $queue), "از آرشیو خارج شد");
     }*/

    /*public function archivedList()
    {
        $users = Queue::onlyTrashed()->orderBy("deleted_at", "DESC")->paginate(100);
        return view('back.queues.trash', compact("queues"));
    }*/


    public function addUser(Request $request)
    {

        $this->validate($request, [
            "queue_id" => "required",
            "user_id" => "required",
        ]);

        $user = User::findOrFail($request->user_id);
        $queue = Queue::findOrFail($request->queue_id);


        /* if (config('nasimMoshaver.syncWithSimotel', true)) {
             $simotelApi = new SimotelApi();
             $apiResult = $simotelApi->addToQueue($queue->simotel_number, $user->simotel_number, $user->simotel_number);
             if (!$apiResult) {
                 $message = new MessageBag();
                 $message->add("simotelApi", $simotelApi->getMessage());
                 return redirect()->back()->withErrors($message);
             }
         }*/

        if ($queue->users()->where("users.id", $user->id)->first()) {
            $message = new MessageBag();
            $message->add("user_id", "کاربر انتخاب شده در صف وجود دارد");
            return redirect()->back()->withErrors($message);
        }

        $queue->users()->attach($user);
        return self::redirectBackWithSuccess("انجام شد.");
    }

    /*
        public function changeStatus(Request $request)
        {
            $user = User::findOrFail($request->user_id);
            $queue = Queue::findOrFail($request->queue_id);

            $message = new MessageBag();

            if (config('nasimMoshaver.syncWithSimotel', true)) {
                $simotelApi = new SimotelApi();

                if ($request->active)
                    $apiResult = $simotelApi->resumeInQueue($queue->simotel_number, $user->simotel_number);
                else
                    $apiResult = $simotelApi->pauseInQueue($queue->simotel_number, $user->simotel_number);

                if (!$apiResult)
                    $message->add("simotelApiQueue", $simotelApi->getMessage());
            }

            if ($message->isEmpty())
                $queue->users()->updateExistingPivot($user, ["active" => $request->active]);



            $queue = $queue->users()->whereUserId($user->id)->first();

            return response()->json($queue->pivot);


        }*/

    public function removeUserFromQueue(Request $request)
    {
        $queue = Queue::findOrFail($request->queue_id);
        $user = User::findOrFail($request->user_id);
        if (config('nasimMoshaver.syncWithSimotel', true)) {
            $simotelApi = new SimotelApi();
            $apiResult = $simotelApi->removeFromQueue($queue->simotel_number, $user->simotel_number);
            if (!$apiResult) {
                $message = new MessageBag();
                $message->add("simotelApi", $simotelApi->getMessage());
                return redirect()->back()->withErrors($message);
            }
        }

        $queue->users()->detach($request->user_id);
        return self::redirectBackWithSuccess("از صف خارج شد");
    }

}

resources/views/back/queues/_form.blade.php
<form action="{{ route('admin.queues.store')  }}"
      method="post" enctype="multipart/form-data">
    @csrf
    {{ Html::hidden()->name('queue_id')->value($queue->id)->when( $action=='edit') }}
    {{ Html::method()->value("PUT")->when($action=='edit') }}
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    {{
                    Html::text("name")
                    ->value(old("name",$queue->name))
                    ->label("عنوان صف")
                    ->description("جهت نمایش در نرم افزار مشاور")
                     }}
                    {{
                    Html::text("announcement_id")
                    ->value(old("announcement_id",$queue->announcement_id))
                    ->label("شناسه معرفی صف")
                    ->description("شناسه اعلام شده توسط آوای انتخاب صف در نقشه تماس سیموتل")
                     }}
                    {{
                    Html::text("simotel_number")
                    ->value(old("simotel_number",$queue->simotel_number))
                    ->label("شماره داخلی سیموتل")
                     }}
                    {{
                    Html::text("credit_ratio")
                    ->value(old("credit_ratio",$queue->credit_ratio))
                    ->label("ضریب کسر اعتبار")
                    ->description("کسر هزینه(تومان) به ازای هر دقیقه مکالمه")
                     }}
                    {{
                    Html::text("entrance_fee")
                    ->value(old("entrance_fee",$queue->entrance_fee)  ?? 0)
                    ->label("هزینه ورودی")
                    ->description("به تومان")
                     }}
                    {{ Html::text("comment")
                        ->value(old("comment",$queue->comment))
                        ->label("توضیحات")
                        ->description("")
                    }}

                <div class="row">
                    <div class="col-md-12">
                        <div class="pull-left">{{ Html::submit()->label('ذخیره') }}</div>
                    </div>
                </div>
                </div>
            </div>

        </div>
    </div>
</form>

resources/views/back/queues/all.blade.php
@extends("back.layout.app")
@section("content_header")
    @component("components.breadcrump",["items"=> ["Dashboard" =>route("admin.dashboard.index"),"current"=>"صف ها"]])
        <a href="{{ route("admin.queues.create") }}" class="btn btn-info btn-sm">جدید</a>
    @endcomponent
@endsection

@php
    use Hsy\Html\Facades\Html;
@endphp
@section("content")
    <x-success></x-success>
    {{ $queues->render() }}
    <div class="card">
        <div class="card-body">
            <table class="table">
                <thead>
                <tr>
                    <th></th>
                    <th>نام</th>
                    <th>شماره</th>
                    <th>تعداد کاربر</th>
                    <th>فی ورودی</th>
                    <th>ضریب کسر اعتبار</th>
                </tr>
                </thead>
                <tbody>
                @foreach($queues as $queue)
                    <tr>
                        <td></td>
                        <td><a href="{{ route("admin.queues.show",$queue) }}">{{ $queue->name }}</a></td>
                        <td>{{ $queue->simotel_number }}</td>
                        <td>{{ $queue->users_count }}</td>
                        <td>{{ $queue->entrance_fee }}</td>
                        <td>{{ $queue->credit_ratio }}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/back/queues/create.blade.php
@extends("back.layout.app")
@section("content_header")
    @component("components.breadcrump",
    ["items"=> ["Dashboard" =>route("admin.dashboard.index"),"Queues" =>route("admin.queues.index"),"current"=>"تعریف صف جدید"]])
    @endcomponent
@endsection

@php
    use Hsy\Html\Facades\Html;
@endphp
@section("content")
    <x-success></x-success>
    <x-errors></x-errors>
        @include("back.queues._form",["action"=>"create"])
@endsection

resources/views/back/queues/edit.blade.php
@extends("back.layout.app")
@section("content_header")
    @component("components.breadcrump",
    ["items"=> ["Dashboard" =>route("admin.queues.index"),"Users" =>route("admin.queues.index"),"current"=>"ویرایش اطلاعات صف"]])
    @endcomponent
@endsection

@php
    use Hsy\Html\Facades\Html;
@endphp
@section("content")
    <x-success></x-success>
        @include("back.queues._form",["action"=>"edit"])
@endsection

resources/views/back/queues/show.blade.php
@extends("back.layout.app")
@section("content_header")
    @component("components.breadcrump",
    ["items"=> ["Dashboard" =>route("admin.dashboard.index"),"Queues" =>route("admin.queues.index"),"current"=>"مشاهده وضعیت صف"]])
    @endcomponent
@endsection
@php
    use Hsy\Html\Facades\Html;
@endphp
@section("content")


    <x-success></x-success>
    <div class="row">
        <div class="col-md-6 mb-4">
            <div class="card ">
                <div class="card-header">
                    اطلاعات صف
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="text-success h4"><i class="fa fa-user"></i> {{ $queue->name }} </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            {{ Html::info()->value($queue->credit_ratio)->label("ضریب کسر اعتبار")->icon("money") }}
                            {{ Html::info()->value($queue->entrance_fee)->label("هزینه ورودی")->icon("money") }}
                            {{ Html::info()->value($queue->simotel_number)->label("داخلی سیموتل")->icon("phone") }}
                        </div>
                        <div class="col-md-6">
{{--                            {{ Html::info()->value($queue->comment)->label("توضیحات")->icon("info") }}--}}
{{--                            {{ Html::info()->value($queue->created_at_fa_ftt)->label("زمان ثبت نام صف")->icon("plus") }}--}}
{{--                            {{ Html::info()->value($queue->updated_at_fa_ftt)->label("زمان آخرین ویرایش")->icon("edit") }}--}}
                        </div>
                    </div>

                </div>
                <div class="card-footer">
                    <div class="float-left">
                        <a class="btn btn-outline-success btn-sm" href="{{ route("admin.queues.edit",$queue) }}"><i
                                class="fa fa-edit"></i> ویرایش مشخصات </a>
                        <a class="btn btn-danger btn-sm confirmation" href="{{ route("admin.queues.destroy",$queue) }}">
                            <i class="fa fa-edit"></i>حذف صف </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6 mb-4">
            <div class="card ">
                <div class="card-header">
                    گزارش
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <calls-report :queue_id="{{ json_encode($queue->id) }}"></calls-report>
                        </div>
                    </div>

                </div>
                <div class="card-footer">
                    <div class="float-left">

                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-6">

            <div class="card">
                <div class="card-header">افزودن کاربر به صف</div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <x-errors></x-errors>
                        </div>
                    </div>
                    <form action="{{ route('admin.queues.add')  }}"
                          method="post">
                        @csrf
                        {{ Html::hidden()->name('queue_id')->value($queue->id) }}
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group ">
                                    <label for="user_select" class="col-form-label text-md-right">نام کاربر</label>
                                    <x-select-user></x-select-user>
                                    <small>کاربر مورد نظر خود را انتخاب کنید</small>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="pull-left">{{ Html::submit()->label('ذخیره') }}</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
        <div class="col-md-6">

            <div class="card">
                <div class="card-header">مشاورین حاضر در صف</div>

                <div class="card-body">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>کاربر</th>
                            <th>داخلی سیموتل</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($queue->users as $user)
                            <tr>
                                <td>{{ $user->name }}</td>
                                <td>{{ $user->simotel_number }}</td>

                                <td>
                                    <form action="{{ route("admin.queues.removeUserFromQueue") }}" method="post">
                                        @csrf
                                        @method("DELETE")
                                        {{ Html::hidden("user_id")->value($user->id) }}
                                        {{ Html::hidden("queue_id")->value($queue->id) }}
                                        <button type="submit" class="btn btn-link text-danger"><i
                                                class="fa fa-window-close "></i></button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <div class="col-md-12 mb-4">
            <div class="card ">
                <div class="card-header">
                    آخرین تماس ها
                </div>
                <div class="card-body">
                    @php
                        $report = new \App\Classes\Reports\CallsReports();

                    @endphp

                    <table class="table">
                        <thead>
                        <tr>
                            <th>تاریخ</th>
                            <th>ساعت</th>
                            <th>مدت مکالمه</th>
                            <th>مشاور</th>
                            <th>شماره ورودی</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($report->getCalls($queue->id) as $call)
                            <tr>
                                <td>{{ $call->created_at_fa_f }}</td>
                                <td>{{ $call->created_at->format("H:i:s") }}</td>
                                <td>{{ $call->call_time_readable_short }}</td>
                                <td>{{ $call->user->name }}</td>
                                <td>{{ $call->src_number }}</td>
                                <td>{{ $call->created_at->ago() }}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                <div class="card-footer">
                    <div class="float-left">

                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-12 mb-4">
            <div class="card ">
                <div class="card-header">
درامد مشاورین
                </div>
                <div class="card-body">
                    @php
                        $report = new \App\Classes\Reports\CallsReports();

                    @endphp

                    <table class="table">
                        <thead>
                        <tr>
                            <th>مشاور</th>
                            <th>درامد</th>
                            <th>تعداد تماس</th>
                            <th>مجموع زمان</th>
                            <th>میانگین امتیاز</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($report->usersReport($queue->id) as $report)
                            <tr>
                                <td>{{ $report->user->name }}</td>
                                <td>{{ $report->total_amount }}</td>
                                <td>{{ $report->calls_count }}</td>
                                <td>{{ $report->call_time_readable_short }}</td>
                                <td>{{ $report->poll_score_avg }}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                <div class="card-footer">
                    <div class="float-left">

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection