routes/admin.php
<?php

use Illuminate\Support\Facades\Route;


Route::namespace("\App\Http\Controllers\Back")->middleware(["auth","auth.admin"])->prefix("admin")->as("admin.")
    ->group(function () {

        Route::get("/", "DashboardController@index")->name("dashboard.index");

        Route::get("users/getUsers", "UserController@getUsers")->name("users.getUsers");
        Route::resource("users", "UserController")->except(["update", "store","destroy"]);
        Route::match(['PUT', "POST"], "users", "UserController@store")->name("users.store");
        Route::get("users/{user}/destroy", "UserController@destroy")->name("users.destroy");
        Route::get("users/{user}/archive", "UserController@archive")->name("users.archive");
        Route::get("users/{user}/recycle", "UserController@recycle")->name("users.recycle");
        Route::get("users/archived/list", "UserController@archivedList")->name("users.archive.index");
        Route::get("users/schedule/{user}", "UserController@scheduleForm")->name("users.schedule.form");

        Route::get("search/users", "SearchController@searchForUser")->name("search.users");

        Route::get("credits", "CreditController@index")->name("credits.index");

        Route::get("credits/show/{credit}", "CreditController@show")->name("credits.show");
        Route::post("credits/addCharge/{credit}", "CreditController@addCharge")->name("credits.addCharge");
        Route::get("credits/createUniqueUrl/{credit}", "CreditController@createUniqueUrl")->name("credits.createUniqueUrl");

        Route::get("creditGroups", "CreditGroupController@index")->name("creditGroups.index");
        Route::get("creditGroups/create", "CreditGroupController@create")->name("creditGroups.create");
        Route::post("creditGroups/{creditGroup}/createPins", "CreditGroupController@storePins")->name("creditGroups.storePins");
        Route::get("creditGroups/{creditGroup}/getCredits", "CreditGroupController@getGreditsOfGroup")->name("creditGroups.getCreditsOfGroup");
        Route::get("creditGroups/{creditGroup}/destroy", "CreditGroupController@destroy")->name("creditGroups.destroy");

        Route::get("creditGroups/{creditGroup}", "CreditGroupController@show")->name("creditGroups.show");
        Route::post("creditGroups", "CreditGroupController@store")->name("creditGroups.store");
        Route::get("creditGroups/{creditGroup}/download", "CreditGroupController@download")->name("creditGroups.download");


        Route::resource("queues", "QueueController")->except(["update", "store","destroy"]);
        Route::match(['PUT', "POST"], "queues", "QueueController@store")->name("queues.store");
        Route::get("queues/{queue}/destroy", "QueueController@destroy")->name("queues.destroy");
        Route::post("queues/addUser", "QueueController@addUser")->name("queues.add");
        Route::post("queues/changeStatus", "QueueController@changeStatus")->name("queues.changeStatus");
        Route::delete("queues/users/removeFromQueue", "QueueController@removeUserFromQueue")->name("queues.removeUserFromQueue");

        Route::get("calls","CallController@index")->name("calls.index");
        Route::get("calls/getCalls","CallController@getCalls")->name("calls.getCalls");
        Route::get("calls/{call}","CallController@show")->name("calls.show");

        Route::get("reports/calls", "ReportController@calls");

        Route::get("changePassword", "PasswordController@form")->name("changePasswordForm");
        Route::post("changePassword", "PasswordController@update")->name("changePassword");

        Route::get("search", "SearchController@search")->name("search");

        Route::get("options", "OptionsController@index")->name("options.index");
        Route::post("options", "OptionsController@store")->name("options.store");

    });

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::namespace("\App\Http\Controllers\Front")->as("front.")
    ->group(function () {
        Route::get("/", "HomeController@index")->name("home.index");

        Route::post("/purchase", "PurchaseController@purchase")->name("purchase");
        Route::get("/purchase/verify/{driver}", "PurchaseController@verify")->name("purchase.verify");

        Route::get("/credits/{unique_id}", "CreditController@show")->name("credits.show");
        Route::post("/credits/updatePhoneNumber", "CreditController@updatePhoneNumber")->name("credits.updatePhoneNumber");

        Route::get("/payments/fails", "PaymentController@fails")->name("payments.fails");

        Route::get("syncQueues", function () {
            $sync = new \App\Classes\Simotel\SyncUsersInQueues();
            $sync->syncAll();
        });

    });

Auth::routes(["register" => false]);

Route::any("/clear", function () {
    \Illuminate\Support\Facades\Artisan::call("view:clear");
});
Route::any("/migrate/fresh", function () {
    \Illuminate\Support\Facades\Artisan::call("migrate:fresh");
});

Route::get("shetabit/start", "ShetabitTestController@start");
Route::get("shetabit/verify", "ShetabitTestController@verify")->name("shetabit.verify");

Route::get("users/test", "TestController@users");
Route::get("users/data", "TestController@usersData")->name("users.data");

Route::get("fields", function () {
    $class = new \App\Classes\Simotel\SimotelSettings();
    dd($class->getGroupedFields());
});

Route::get("firstuser", function () {
    $user = \App\User::find(1);
    $user->level = \App\User::LEVEL_ADMIN;
    $user->password = bcrypt("asd123ASD");
    $user->save();
});

Route::get("createuseradmin", function () {
    if(\App\User::count()>0)
        die("exists");

    \App\User::create([
        'name' => 'username',
        'email' => request("email"),
        'password' => bcrypt("asd123ASD"),
        'simotel_number' => "",
        'mobile' => "",
        'comment' => "",
        'address' => "تهران، آدرس مربوط به محل کاربر ادمین",
        'level' =>  \App\User::LEVEL_ADMIN,
        'entrance_fee' => "1000",
        'credit_ratio' => "1000",
    ]);

});

Route::get("logtest", function () {
    \Illuminate\Support\Facades\Log::info("test");
});


Route::get("ternary", function () {
    return view("ternary");
});


Route::get("/test/simotel","TestController@simotel");

app/Models/Call.php
<?php

namespace App\Models;

use App\User;
use Baloot\EloquentHelper;
use Carbon\CarbonInterval;
use Illuminate\Database\Eloquent\Model;

class Call extends Model
{
    use EloquentHelper;


    public function putCredit($credit)
    {
        $this->credit_id = $credit->id;
        $this->save();
    }

    public function queue()
    {
        return $this->belongsTo(Queue::class)->withDefault(['name' => ""]);
    }

    public function user()
    {
        return $this->belongsTo(User::class)->withDefault(['name' => ""]);
    }


    public function getCallTimeReadableShortAttribute()
    {
        return $this["call_time"] ? secondsToShortTime($this["call_time"]) : "0";
    }

    public function getCallTimeReadableAttribute()
    {
        return $this["call_time"] ? CarbonInterval::seconds($this['call_time'])->cascade()->forHumans() : "0";
    }
    public function getTotalAmountReadableAttribute()
    {
        return number_format($this["total_amount"]);
    }

    function getHoursMinutes($seconds)
    {

        $hours = floor($seconds / 3600);
        $minutes = floor(($seconds - ($hours * 60 * 60)) / 60);
        $seconds = $seconds - $hours*3600 - $minutes*60;
        return sprintf("%d:%d:%d",
            $hours,
            $minutes,
            $seconds
        );
    }

    public function credit(){
        return $this->belongsTo(Credit::class);
    }

    protected $casts = [
        'create_date' => 'date',
    ];
}

app/Models/Credit.php
<?php

namespace App\Models;

use App\User;
use Baloot\EloquentHelper;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class Credit extends Model
{
    use EloquentHelper;

    public function getUniqueUrlAttribute()
    {
        return route("front.credits.show", $this->unique_id);
    }


    public static function createNew($amount, $phone_number = null, $creditGroupId = null)
    {
        $credit = new Credit;
        $credit->identifier = self::createRandomPin();
        $credit->unique_id = self::creditUniqueId();
        $credit->phone_number = $phone_number;
        $credit->credit_group_id = $creditGroupId;
        $credit->creator_id = Auth::user() ? Auth::user()->id : null;
        $credit->save();

        $credit->chargeCredit($amount);

        return $credit;
    }

    public function changeUniqueId()
    {
        $this->unique_id = self::creditUniqueId();
        $this->save();
        return $this;
    }

    public function creator()
    {
        return $this->belongsTo(User::class, "creator_id")->withDefault([
            "name" => ""
        ]);
    }

    public function creditGroup()
    {
        return $this->belongsTo(CreditGroup::class);
    }

    public function chargeCredit($amount)
    {
        $this->charges()->create([
            'amount' => $amount,
            'creator_id' => Auth::user() ? Auth::user()->id : null,
        ]);
    }

    public function charges()
    {
        return $this->hasMany(CreditCharges::class);
    }

    public function calls()
    {
        return $this->hasMany(Call::class);
    }


    public function getTotalCreditAttribute()
    {
        return $this->charges->sum("amount");
    }

    public function getTotalUsageAttribute()
    {
        return $this->calls->sum("total_amount");
    }

    public function getRemainCreditAttribute()
    {
        return $this->total_credit - $this->total_usage;
    }


    public function scopeLike($query, $field, $value)
    {
        return $query->where($field, 'LIKE', "%$value%");
    }

    public function scopeOrlike($query, $field, $value)
    {
        return $query->orWhere($field, 'LIKE', "%$value%");
    }


    private static function creditUniqueId()
    {
        do {
            $uniqueId = Str::random(10);
            $credit = \App\Models\Credit::whereUniqueId($uniqueId)->first();
        } while (!empty($credit));

        return $uniqueId;

    }

    public static function createRandomPin()
    {

        $min = pow(10, config("nasimMoshaver.pincodeDigitsCount", 8) - 1);
        $max = pow(10, config("nasimMoshaver.pincodeDigitsCount", 8)) - 1;
        $ignoreCount = 0;
        while ($ignoreCount < 1000) {
            $randomPin = rand($min, $max);
            $credit = Credit::whereIdentifier($randomPin)->first();
            if (!$credit)
                return $randomPin;

            $ignoreCount++;
        }

        return null;

    }

}

app/Models/CreditCharges.php
<?php

namespace App\Models;

use App\User;
use Baloot\EloquentHelper;
use Illuminate\Database\Eloquent\Model;

class CreditCharges extends Model
{
    use EloquentHelper;
    protected $fillable=['amount','comment','creator_id'];
    public function credit()
    {
        return $this->belongsTo(Credit::class);
    }

    public function getAmountReadableAttribute()
    {
        return number_format($this->amount);
    }

    public function creator()
    {
        return $this->belongsTo(User::class,"creator_id")->withDefault([
            "name"=>""
        ]);
    }
}

app/Http/Controllers/Back/AdvisorQueueController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AdvisorQueueController extends Controller
{
    public function __construct()
    {
    }

    public function index()
    {
        $user = Auth::user();

        $queues =
            $user
                ->queues()
                ->join("calls", "queues.id", "calls.queue_id")
                ->join("calls","users.id","calls.user_id")
        ->get();
        dd($queues);
    }
}

app/Http/Controllers/Back/CallController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\Models\Call;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Yajra\DataTables\Facades\DataTables;

class CallController extends Controller
{
    public function index()
    {
        return view("back.calls.all");
    }

    public function getCalls()
    {
        $calls = Call::select(DB::raw("calls.* , users.name as user_name , queues.name as queue_name"))
            ->join("queues", "queues.id", "calls.queue_id")
            ->join("users", "users.id", "calls.user_id");

        return DataTables::of($calls)

            ->addColumn('user_name_str', function ($row) {
                return "<a href='" . route("admin.users.show", $row->user_id) . "'>$row->user_name</a>";
            })
            ->addColumn('queue_name_str', function ($row) {
                return "<a href='" . route("admin.queues.show", $row->queue_id) . "'>$row->queue_name</a>";
            })
            ->addColumn('created_at_fa_ftt', function ($row) {
                return "<a href='" . route("admin.calls.show", $row->id) . "'>$row->created_at_fa_ftt</a>";
            })
            ->addColumn('call_time_readable', function ($row) {
                return $row->call_time_readable_short;
            })
            ->addColumn('total_amount_formatted', function ($row) {
                return number_format($row->total_amount);
            })

            ->rawColumns(['user_name_str', "queue_name_str","created_at_fa_ftt"])
            ->make(true);
    }

    public function show()
    {

    }
}

app/Http/Controllers/Back/CreditController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\Models\Call;
use App\Models\Credit;
use App\Models\CreditCharges;
use App\Models\CreditGroup;
use App\Models\CreditGroups;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class CreditController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $credits = Credit
            ::select(
                DB::raw("`credits`.`id`,`identifier`,sum(`credit_charges`.`amount`) as `sum_credit` , sum(`calls`.`total_amount`) as `total_usage` ")
            )
            ->join('credit_charges', 'credits.id', "=", "credit_charges.credit_id")
            ->leftJoin("calls", 'credits.id', '=', 'calls.credit_id')
            ->groupBy("credits.id")
            ->get();
        return view("back.credits.all", compact("credits"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
 /*   public function create()
    {
        $credit = new Credit();
        return view("back.credits.create", compact("credit"));
    }*/

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
 /*   public function store(Request $request)
    {

        $this->validate($request,
            [
                "amount" => "required|numeric",
            ]
        );

       Credit::createNew($request->amount,$request->customer_number);

        return self::redirectWithSuccess(route("admin.credits.index"), "اطلاعات ذخیره شد");
    }*/

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Credit $credit
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Credit $credit)
    {
        $credit->load("charges", "calls", 'calls.user', 'calls.queue');
        return view("back.credits.show", compact('credit'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Credit $credit
     * @return \Illuminate\Http\Response
     */
    public function edit(Credit $credit)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Credit $credit
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Credit $credit)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Credit $credit
     * @return \Illuminate\Http\Response
     */
    public function destroy(Credit $credit)
    {
        //
    }


    public function addCharge(Request $request, Credit $credit)
    {
        $this->validate($request, [
            'amount' => "required|numeric"
        ]);
        $credit->charges()->create([
            'amount' => $request->amount,
            'comment' => $request->comment,
            'creator_id' => Auth::user() ? Auth::user()->id : null ,
        ]);

        return self::redirectBackWithSuccess("عملیات شارژ انجام شد");
    }


    public function createUniqueUrl(Credit $credit)
    {
        $credit->changeUniqueId();
        return self::redirectBackWithSuccess("لینک منحصر به فرد ایجاد شد.");
    }

}

app/Http/Controllers/Back/PasswordController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class PasswordController extends Controller
{
    public function form(){
        return view("back.changePassword");
    }

    public function update(Request $request){
        $this->validate($request,[

            'password' => ['required', 'string', 'min:8', 'confirmed'],
        ]);
        $user = Auth::user();
        $user->password = bcrypt($request->password);
        $user->save();

        return self::redirectBackWithSuccess("تغییر رمز با موفقیت انجام شد");
    }
}

resources/views/back/credits/show.blade.php
@extends("back.layout.app")
@section("content_header")
    @component("components.breadcrump",
    ["items"=> ["Dashboard" =>route("admin.dashboard.index"),$credit->creditGroup->title =>route("admin.creditGroups.show",$credit->creditGroup),"current"=>"مشاهده شناسه اعتبار"]])
    @endcomponent
@endsection
@php
    use Hsy\Html\Facades\Html;
@endphp
@section("content")
    <x-success></x-success>
    <div class="row">
        <div class="col-md-6 mb-4">
            <div class="card ">
                <div class="card-header">
                    اطلاعات شناسه اعتبار
                </div>
                <div class="card-body">
                    {{ Html::info()->value($credit->identifier)->label("شناسه")->icon("key") }}
                    {{ Html::info()->value($credit->phone_number)->label("شماره تلفن اختصاصی")->icon("") }}
                    {{ Html::info()->value(number_format($credit->total_credit)." تومان ")->label("مجموع مبلغ شارژ شده")->icon("coins") }}
                    {{ Html::info()->value(number_format($credit->total_usage)." تومان ")->label("مجموع اعتبار کسر شده")->icon("donate") }}
                    {{ Html::info()->value(number_format($credit->remain_credit) ." تومان ")->label("مانده اعتبار")->icon("money-check-alt") }}
                    {{ Html::info()->value("")->label("مجموع زمان مکالمات")->icon("business-time") }}


                </div>

                <div class="card-footer">
                    <div class="float-left">
                      {{--   <a class="btn btn-outline-success btn-sm" href="{{ route("admin.users.edit",$user) }}"><i
                                class="fa fa-edit"></i> ویرایش مشخصات </a>
                                <a class="btn btn-warning btn-sm" href="{{ route("admin.users.archive",$user) }}"><i
                                class="fa fa-recycle"></i> آرشیو</a>
                                <a class="btn btn-danger btn-sm confirmation" href="{{ route("admin.users.destroy",$user) }}"><i
                                class="fa fa-trash"></i> حذف دائم</a> --}}
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6 mb-4">
            <div class="card ">
                <div class="card-header">لینک یکتا</div>
                <div class="card-body text-left">
                    @if($credit->unique_id)
                        <div>
                            <a href="{{ $credit->unique_url }}" target="_blank">{{ $credit->unique_url }}</a>
                        </div>
                        <div>
                            <a href="{{ route("admin.credits.createUniqueUrl",$credit)}}"
                               class="btn btn-sm btn-outline-success">تولید لینک جدید</a>
                        </div>
                    @else
                        تا کنون برای این کارت اعتباری لینک یکتا ایجاد نشده است.
                        <div>
                            <a href="{{ route("admin.credits.createUniqueUrl",$credit)}}"
                               class="btn btn-sm btn-outline-success">تولید لینک جدید</a>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">افزایش اعتبار</div>

                <div class="card-body">
                    <form action="{{ route("admin.credits.addCharge",$credit) }}" method="post">
                        @csrf


                        <div class="row">
                            <div class="col-md-12">
                                {{
                       Html::text("amount")
                       ->value(old("amount",$credit->amount))
                       ->label("مبلغ اعتبار")
                       ->description("به تومان")
                        }}
                            </div>
                            <div class="col-md-12">
                                {{
                       Html::text("comment")
                       ->value(old("comment"))
                       ->label("توضیحات")
                       ->description("در صورت نیاز به توضیح")
                        }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="pull-left">{{ Html::submit()->label('افزودن اعتبار') }}</div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-6 mb-4">
            <div class="card ">
                <div class="card-header">
                    شارژ های انجام شده
                </div>
                <div class="card-body">
                    <table class="table ">
                        <thead>
                        <tr>
                            <th>مقدار اعتبار</th>
                            <th>زمان ایجاد</th>
                            <th></th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($credit->charges as $charge)
                            <tr>
                                <td>{{ $charge->amount_readable }}</td>
                                <td>{{ $charge->created_at_fa_ft }}</td>
                                <td>{{ $charge->comment }}</td>
                                <td>{{ $charge->creator->name }}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 mb-4">
            <div class="card ">
                <div class="card-header">تاریخچه تماس ها</div>
                <div class="card-body">
                    <table class="table ">
                        <thead>
                        <tr>
                            <th>شماره ورودی</th>
                            <th>هزینه ورودی</th>
                            <th>هزینه هر دقیقه</th>
                            <th>مدت تماس</th>
                            <th>هزینه تماس</th>
                            <th>جمع هزینه</th>
                            <th>صف</th>
                            <th>مشاور پاسخگو</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($credit->calls as $call)
                            <tr>
                                <td>{{ $call->src_number }}</td>
                                <td>{{ number_format($call->entrance_fee) }}</td>
                                <td>{{ number_format($call->credit_ratio) }}</td>
                                <td>{{ $call->call_time_readable }}</td>
                                <td>{{ number_format($call->call_amount) }}</td>
                                <td>{{ number_format($call->total_amount) }}</td>
                                <td>{{ $call->queue->name }}</td>
                                <td>{{ $call->user->name }}</td>
                                <td>{{ $call->created_at_fa_ft }}</td>
                            </tr>
                        @endforeach
                        </tbody>
                        <tfoot>
                        <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td>{{ number_format($credit->total_usage) }} تومان</td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                        </tfoot>
                    </table>
                </div>
                <div class="card-footer">
                    <div class="float-left">
                        {{-- <a class="btn btn-outline-success btn-sm" href="{{ route("admin.users.edit",$user) }}"><i
                                 class="fa fa-edit"></i> ویرایش مشخصات </a>
                         <a class="btn btn-outline-success btn-sm" href="{{ route("admin.users.archive",$user) }}"> آرشیو
                             <i class="fa fa-archive"></i> </a>--}}
                    </div>
                </div>
            </div>
        </div>


    </div>
@endsection