routes/admin.php
<?php

use Illuminate\Support\Facades\Route;


Route::namespace("\App\Http\Controllers\Back")->middleware(["auth","auth.admin"])->prefix("admin")->as("admin.")
    ->group(function () {

        Route::get("/", "DashboardController@index")->name("dashboard.index");

        Route::get("users/getUsers", "UserController@getUsers")->name("users.getUsers");
        Route::resource("users", "UserController")->except(["update", "store","destroy"]);
        Route::match(['PUT', "POST"], "users", "UserController@store")->name("users.store");
        Route::get("users/{user}/destroy", "UserController@destroy")->name("users.destroy");
        Route::get("users/{user}/archive", "UserController@archive")->name("users.archive");
        Route::get("users/{user}/recycle", "UserController@recycle")->name("users.recycle");
        Route::get("users/archived/list", "UserController@archivedList")->name("users.archive.index");
        Route::get("users/schedule/{user}", "UserController@scheduleForm")->name("users.schedule.form");

        Route::get("search/users", "SearchController@searchForUser")->name("search.users");

        Route::get("credits", "CreditController@index")->name("credits.index");

        Route::get("credits/show/{credit}", "CreditController@show")->name("credits.show");
        Route::post("credits/addCharge/{credit}", "CreditController@addCharge")->name("credits.addCharge");
        Route::get("credits/createUniqueUrl/{credit}", "CreditController@createUniqueUrl")->name("credits.createUniqueUrl");

        Route::get("creditGroups", "CreditGroupController@index")->name("creditGroups.index");
        Route::get("creditGroups/create", "CreditGroupController@create")->name("creditGroups.create");
        Route::post("creditGroups/{creditGroup}/createPins", "CreditGroupController@storePins")->name("creditGroups.storePins");
        Route::get("creditGroups/{creditGroup}/getCredits", "CreditGroupController@getGreditsOfGroup")->name("creditGroups.getCreditsOfGroup");
        Route::get("creditGroups/{creditGroup}/destroy", "CreditGroupController@destroy")->name("creditGroups.destroy");

        Route::get("creditGroups/{creditGroup}", "CreditGroupController@show")->name("creditGroups.show");
        Route::post("creditGroups", "CreditGroupController@store")->name("creditGroups.store");
        Route::get("creditGroups/{creditGroup}/download", "CreditGroupController@download")->name("creditGroups.download");


        Route::resource("queues", "QueueController")->except(["update", "store","destroy"]);
        Route::match(['PUT', "POST"], "queues", "QueueController@store")->name("queues.store");
        Route::get("queues/{queue}/destroy", "QueueController@destroy")->name("queues.destroy");
        Route::post("queues/addUser", "QueueController@addUser")->name("queues.add");
        Route::post("queues/changeStatus", "QueueController@changeStatus")->name("queues.changeStatus");
        Route::delete("queues/users/removeFromQueue", "QueueController@removeUserFromQueue")->name("queues.removeUserFromQueue");

        Route::get("calls","CallController@index")->name("calls.index");
        Route::get("calls/getCalls","CallController@getCalls")->name("calls.getCalls");
        Route::get("calls/{call}","CallController@show")->name("calls.show");

        Route::get("reports/calls", "ReportController@calls");

        Route::get("changePassword", "PasswordController@form")->name("changePasswordForm");
        Route::post("changePassword", "PasswordController@update")->name("changePassword");

        Route::get("search", "SearchController@search")->name("search");

        Route::get("options", "OptionsController@index")->name("options.index");
        Route::post("options", "OptionsController@store")->name("options.store");

    });

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::namespace("\App\Http\Controllers\Front")->as("front.")
    ->group(function () {
        Route::get("/", "HomeController@index")->name("home.index");

        Route::post("/purchase", "PurchaseController@purchase")->name("purchase");
        Route::get("/purchase/verify/{driver}", "PurchaseController@verify")->name("purchase.verify");

        Route::get("/credits/{unique_id}", "CreditController@show")->name("credits.show");
        Route::post("/credits/updatePhoneNumber", "CreditController@updatePhoneNumber")->name("credits.updatePhoneNumber");

        Route::get("/payments/fails", "PaymentController@fails")->name("payments.fails");

        Route::get("syncQueues", function () {
            $sync = new \App\Classes\Simotel\SyncUsersInQueues();
            $sync->syncAll();
        });

    });

Auth::routes(["register" => false]);

Route::any("/clear", function () {
    \Illuminate\Support\Facades\Artisan::call("view:clear");
});
Route::any("/migrate/fresh", function () {
    \Illuminate\Support\Facades\Artisan::call("migrate:fresh");
});

Route::get("shetabit/start", "ShetabitTestController@start");
Route::get("shetabit/verify", "ShetabitTestController@verify")->name("shetabit.verify");

Route::get("users/test", "TestController@users");
Route::get("users/data", "TestController@usersData")->name("users.data");

Route::get("fields", function () {
    $class = new \App\Classes\Simotel\SimotelSettings();
    dd($class->getGroupedFields());
});

Route::get("firstuser", function () {
    $user = \App\User::find(1);
    $user->level = \App\User::LEVEL_ADMIN;
    $user->password = bcrypt("asd123ASD");
    $user->save();
});

Route::get("createuseradmin", function () {
    if(\App\User::count()>0)
        die("exists");

    \App\User::create([
        'name' => 'username',
        'email' => request("email"),
        'password' => bcrypt("asd123ASD"),
        'simotel_number' => "",
        'mobile' => "",
        'comment' => "",
        'address' => "تهران، آدرس مربوط به محل کاربر ادمین",
        'level' =>  \App\User::LEVEL_ADMIN,
        'entrance_fee' => "1000",
        'credit_ratio' => "1000",
    ]);

});

Route::get("logtest", function () {
    \Illuminate\Support\Facades\Log::info("test");
});


Route::get("ternary", function () {
    return view("ternary");
});


Route::get("/test/simotel","TestController@simotel");

app/Models/Call.php
<?php

namespace App\Models;

use App\User;
use Baloot\EloquentHelper;
use Carbon\CarbonInterval;
use Illuminate\Database\Eloquent\Model;

class Call extends Model
{
    use EloquentHelper;


    public function putCredit($credit)
    {
        $this->credit_id = $credit->id;
        $this->save();
    }

    public function queue()
    {
        return $this->belongsTo(Queue::class)->withDefault(['name' => ""]);
    }

    public function user()
    {
        return $this->belongsTo(User::class)->withDefault(['name' => ""]);
    }


    public function getCallTimeReadableShortAttribute()
    {
        return $this["call_time"] ? secondsToShortTime($this["call_time"]) : "0";
    }

    public function getCallTimeReadableAttribute()
    {
        return $this["call_time"] ? CarbonInterval::seconds($this['call_time'])->cascade()->forHumans() : "0";
    }
    public function getTotalAmountReadableAttribute()
    {
        return number_format($this["total_amount"]);
    }

    function getHoursMinutes($seconds)
    {

        $hours = floor($seconds / 3600);
        $minutes = floor(($seconds - ($hours * 60 * 60)) / 60);
        $seconds = $seconds - $hours*3600 - $minutes*60;
        return sprintf("%d:%d:%d",
            $hours,
            $minutes,
            $seconds
        );
    }

    public function credit(){
        return $this->belongsTo(Credit::class);
    }

    protected $casts = [
        'create_date' => 'date',
    ];
}

app/Models/Schedule.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Schedule extends Model
{

    public function getDayReadableAttribute()
    {
        return [
            "شنبه",
            "یکشنبه",
            "دوشنبه",
            "سه شنبه",
            "چهار شنبه",
            "پنجشنبه",
            "جمعه",
        ][$this['day'] - 1];
    }

    public function getStartTimeFormattedAttribute()
    {
        $arr = explode(":", $this['start_time']);
        unset($arr[2]);
        return implode(":", $arr);
    }

    public function getEndTimeFormattedAttribute()
    {
        $arr = explode(":", $this['end_time']);
        unset($arr[2]);
        return implode(":", $arr);
    }


    public function scopeGregorianDay($q, $day)
    {
        $persianDay = ($day) % 7 + 2;
        return $q->where("day", $persianDay);
    }


    public function scopeOverlappedWith($q, $startTime, $endTime, $day)
    {
        return $q
            ->where("day", $day)
            ->where(function ($q) use ($startTime, $endTime) {
                return $q
                    ->orWhere(function ($q) use ($startTime, $endTime) {
                        return $q->whereTime("start_time", "<=", $startTime)
                            ->whereTime("end_time", ">=", $startTime);
                    })
                    ->orWhere(function ($q) use ($startTime, $endTime) {
                        return $q->whereTime("start_time", "<=", $endTime)
                            ->whereTime("end_time", ">=", $endTime);
                    })
                    ->orWhere(function ($q) use ($startTime, $endTime) {
                        return $q->whereTime("start_time", ">=", $startTime)
                            ->whereTime("end_time", "<=", $endTime);
                    });
            });
    }

}

app/Http/Controllers/Advisor/DashboardController.php
<?php

namespace App\Http\Controllers\Advisor;

use App\Classes\Reports\CallsReports;
use App\Http\Controllers\Controller;
use App\Models\Call;
use App\Models\Queue;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class DashboardController extends Controller
{
    public function index()
    {
        $user = Auth::user();
        $report = new CallsReports();
        $report->setRowsPerPage(10);
        $callsReport = (object)$report->statisitcs(null, $user->id);
        $userLastCalls = $report->getCalls(null, $user->id);
        $userQueues = $user->queues()->withCount("users")->get();
        $callsInQueuesReport = Call::select(DB::raw(
            "queues.id, queues.name , sum(calls.call_time) as calls_time_total ,avg(calls.call_time) as calls_time_avg ,avg(calls.poll_score) as poll_score_avg "
        ))
            ->join("queues", "queues.id", "=", "calls.queue_id")->where("calls.user_id", $user->id)
            ->groupBy("queues.id", "queues.name")->get();

        return view("advisor.dashboard.index", compact("callsReport", "callsInQueuesReport", "userQueues", "user","userLastCalls"));

    }
}

app/Http/Controllers/Advisor/UserController.php
<?php

namespace App\Http\Controllers\Advisor;

use App\Classes\Simotel\SyncUsersInQueues;
use App\Http\Controllers\Controller;
use App\Models\Queue;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class UserController extends Controller
{
    public function profile()
    {
        $user = Auth::user();
        $userQueues = $user->queues()->withCount("users")->get();
        $callsInQueuesReport = Queue::select(DB::raw(
            "queues.id, queues.name , sum(calls.call_time) as calls_time_total ,avg(calls.call_time) as calls_time_avg ,avg(calls.poll_score) as poll_score_avg "
        ))
            ->join("calls", "queues.id", "=", "calls.queue_id")->where("calls.user_id", $user->id)
            ->groupBy("queues.id", "queues.name")->orderBy("calls.call_time")->get()->dd();
    }


    public function changeStatus(Request $request)
    {
        $this->validate($request, [
            "active" => "required|boolean",
        ]);

        $pause = !$request->active;

        $user = Auth::user();
        $user->simotel_paused = $pause;
        $user->save();

        $simotel = new SyncUsersInQueues;

        if ($pause)
            $simotel->pauseUser($user);
        else
            $simotel->unpauseUser($user);


        return response()->json([
            "active" => !$pause
        ]);
    }

    public function schedules()
    {
        $user = Auth::user();
        return view("advisor.schedules.all", compact("user"));
    }
}

app/Http/Controllers/Back/DashboardController.php
<?php

namespace App\Http\Controllers\Back;

use App\Classes\Reports\CallsAnalyze;
use App\Classes\Reports\CallsReports;
use App\Classes\Reports\LoggedInUsers;
use App\Http\Controllers\Controller;
use App\Models\Queue;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class DashboardController extends Controller
{
    public function index()
    {
        $lastMonthCallsAnalyze = (new CallsAnalyze())->lastDaysReport();
        $allCallsAnalyze = (new CallsAnalyze())->first();

        $onlineUsers = (new LoggedInUsers())->users();

        $report = new LoggedInUsers();
//        $report->setDay(Carbon::now()->dayOfWeek);
        $report->setStartTime(Carbon::now()->format("H:i:s"));
        $report->setEndTime(Carbon::now()->addHours(2));
        $scheduledOnlineUsers = $report->users();

        $report = new CallsReports();
        $report->setRowsPerPage(20);
        $recentCalls = $report->getCalls();

        $queues = Queue::select(DB::raw(
            "queues.id, queues.name , sum(calls.call_time) as calls_time_total,sum(`calls`.`total_amount`) as `total_amount` ,avg(calls.call_time) as calls_time_avg ,avg(calls.poll_score) as poll_score_avg "
        ))
            ->join("calls", "queues.id", "=", "calls.queue_id")
            ->groupBy("queues.id", "queues.name")->get();


        return view(
            "back.dashboard.index",
            compact(
                "onlineUsers", "allCallsAnalyze", "queues",
                "recentCalls", "lastMonthCallsAnalyze", "scheduledOnlineUsers"
            )
        );
    }
}

resources/views/advisor/dashboard/index.blade.php
@extends("back.layout.app")
@section("content_header")
    @component("components.breadcrump",["items"=> ["current"=>"داشبورد مشاور"]])
    @endcomponent
@endsection

@php
    use Hsy\Html\Facades\Html;
@endphp
@section("content")
    <x-success></x-success>


    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">

                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-2 col-4 col-xs-offset-3 col-lg-4 col-xl-2">
                            <img src="/images/avatar-placeholder.png" alt="" class="w-100 rounded-circle">
                        </div>
                        <div class="col-md-10 col-lg-8 col-xl-10">
                            <div class="text-success h4"><i class="fa fa-user"></i> {{ $user->name }} </div>
                            {{ Html::info()->value($user->mobile)->label("شماره موبایل")->icon("mobile") }}
                            {{ Html::info()->value($user->simotel_number)->label("داخلی سیموتل")->icon("phone") }}
                            {{ Html::info()->value($user->comment)->label("توضیحات")->icon("info") }}
                            {{ Html::info()->value($user->created_at_fa_ftt)->label("زمان ثبت نام کاربر")->icon("plus") }}
                            {{ Html::info()->value($user->updated_at_fa_ftt)->label("زمان آخرین ویرایش")->icon("edit") }}


                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">

                            <div class="p-5">
                                <user-pause-status
                                    :user="{{ json_encode($user) }}"></user-pause-status>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="row">

                <div class="col-md-6 col-xs-12">
                    <div class="info-box">
                        <span class="info-box-icon bg-success"><i class="fa fa-phone"></i></span>
                        <div class="info-box-content">
                            <span class="info-box-text">کل زمان مکالمات</span>
                            <span class="info-box-number">{{ $callsReport->call_time_readable_short }}</span>
                        </div>
                        <!-- /.info-box-content -->
                    </div>
                    <!-- /.info-box -->
                </div>
                <div class="col-md-6 col-xs-12">
                    <div class="info-box">
                        <span class="info-box-icon bg-danger"><i class="fa fa-star"></i></span>

                        <div class="info-box-content">
                            <span class="info-box-text">میانگین امتیاز</span>
                            <span class="info-box-number">{{ round($callsReport->poll_score_avg,1) }}</span>
                        </div>
                        <!-- /.info-box-content -->
                    </div>
                    <!-- /.info-box -->
                </div>
                <div class="col-md-6 col-xs-12">
                    <div class="info-box">
                        <span class="info-box-icon bg-secondary"><i class="fa fa-phone"></i></span>

                        <div class="info-box-content">
                            <span class="info-box-text">تعداد تماس ها</span>
                            <span class="info-box-number">{{ $callsReport->calls_count }}</span>
                        </div>
                        <!-- /.info-box-content -->
                    </div>
                    <!-- /.info-box -->
                </div>
                <div class="col-md-6 col-xs-12">
                    <div class="info-box">
                        <span class="info-box-icon bg-info"><i class="fa fa-phone"></i></span>

                        <div class="info-box-content">
                            <span class="info-box-text">میانگین زمان مکالمات</span>
                            <span class="info-box-number">{{ $callsReport->average_call_time_readable }}</span>
                        </div>
                        <!-- /.info-box-content -->
                    </div>
                    <!-- /.info-box -->
                </div>
            </div>
        </div>
        <!-- /.col -->
    </div>


    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">صف های فعال</div>
                <div class="card-body">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>نام صف</th>
                            <th>تعداد مشاور</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($userQueues as $queue)
                            <tr>
                                <td>{{ $queue->name }}</td>
                                <td>{{ $queue->users_count }}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">گزارش مکالمات در صف ها</div>
                <div class="card-body">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>نام صف</th>
                            <th>مجموع زمان مکالمه</th>
                            <th>میانگین زمان مکالمه</th>
                            <th>میتگین امتیاز</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($callsInQueuesReport as $report)
                            <tr>
                                <td>{{ $report->name }}</td>
                                <td>{{ secondsToShortTime($report->calls_time_total) }}</td>
                                <td>{{ secondsToShortTime($report->calls_time_avg) }}</td>
                                <td>{{ round($report->poll_score_avg,1) }}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">آخرین تماس ها</div>
                <div class="card-body">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>شناسه مکالمه</th>
                            <th>صف</th>
                            <th>مدت مکالمه</th>
                            <th>امتیاز</th>
                            <th>زمان شروع</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($userLastCalls as $call)
                            <tr>
                                <td>{{ $call->id }}</td>
                                <td>{{ $call->queue->name }}</td>
                                <td>{{ $call->call_time_readable_short }}</td>
                                <td>{{ $call->poll_score }}</td>
                                <td>{{ $call->created_at_fa_ftt }}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>


        <div class="col-md-6">
            <div class="card">
                <div class="card-header">برنامه حضور</div>
                <div class="card-body">
                    <table class="table ">
                        <thead>
                        <tr>
                            <th>روز هفته</th>
                            <th>شروع</th>
                            <th>پایان</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($user->schedules as $schedule)
                            <tr  >
                                <td>{{ $schedule->day_readable }}</td>
                                <td>{{ $schedule->start_time_formatted }}</td>
                                <td>{{ $schedule->end_time_formatted }}</td>

                            </tr>
                        @endforeach
                        </tbody>
                    </table>


                </div>
            </div>
        </div>


    </div>
@endsection